### ISSUE TITLE
Add/edit recipe ingredient

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/repEAT-ios#17]
Add a new view controller to edit a recipe ingredient.

### Sub-tasks

- [x] Create `IngredientViewController` and hook into storyboard. 
- [x] The table view (with static content) should hold cells for the food entity and the quantity (label and numeric text field). 
- [x] Clicking the food cell should push the new `FoodsViewController` onto the navigation stack. 
- [x] The table view should show all foods in the database and be searchable by food name.
- [x] Both view controllers should report data changes and selections back to their parents.
