### ISSUE TITLE
Unit of measure model

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/repEAT-ios#19]
### Sub-tasks

- [x] Add a new entity `UnitOfMeasure`. 
- [x] Reference it from the `Food` entity.
- [x] Initialize the database with a standard list of units.
